language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_b5831132c768_key -iv $encrypted_b5831132c768_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
